### ISSUE TITLE
Enhancement: Half-time beat 32 step grid support

### ISSUE THREAD

**Issue by currentsound** [r3mot/sampler-step#4]
2. If you want to sequence Trap beats, consider adding a toggle button to swap the sequence display from 16x 16th notes to 32x 32nd notes like FL Studio does. Default view in FL Studio is 16 steps but it can be swapped to 32 steps. So if you want to do 140bpm beat with fast rolls you can use 32 steps (32x 32nd notes).

**Comment by r3mot** [comment]
This project is currently undergoing a rebuild, and this feature will be supported in version 2.

The update will also include the ability to adjust the velocity of each hit. Stay tuned for more updates!
