### ISSUE TITLE
Suggestion: Background variation to visually separate steps into groups of 4

### ISSUE THREAD

**Issue by currentsound** [r3mot/sampler-step#5]
3. See how FL Studio uses a different background color for the for steps 4678 and 13,14,15,16 to make it easier to visually see where each group of 4 starts.

**Comment by r3mot** [comment]
Originally, each measure was visually separated, but I found that the combination of the sequencer’s style and the visual separation became distracting.

FL Studio’s UI handles this well by alternating between two colors and adjusting the opacity/brightness when a beat is selected. Adopting a similar approach could work here, though it would change the overall look of the project.

I’ve attached a modified version to see if this aligns with what you’re envisioning. I’m open to feedback and suggestions for further improvements. Let me know your thoughts!

![step-diff](https://github.com/user-attachments/assets/d3505d0d-a266-4918-bc1f-27dc600714df)

**Comment by currentsound** [comment]
Yeah that works

**Comment by currentsound** [comment]
Other option would be to do the background only but the issue with that is, once you make a pattern you're now reliant on looking at other tracks that have less steps used but once they're filled you'll lose your reference.
